// Generated by Wrangler on Sun May 26 2024 15:04:29 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	test: KVNamespace;
	API_HOST: "example.com";
	API_ACCOUNT_ID: "example_user";
	SERVICE_X_DATA: {"URL":"service-x-api.dev.example","MY_ID":123};
	SECRET_KEY: string;
	DB: D1Database;
}
