#:schema node_modules/wrangler/config-schema.json
name = "lively-dew-2cc9"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

# Duplicate preview_id to id
kv_namespaces = [
  { binding = "test", preview_id = "0fe04d28987e40429337c02661c71fb0", id = "0fe04d28987e40429337c02661c71fb0" },
]

# Run `wrangler publish --env production` when happy
[env.production]
kv_namespaces = [{ binding = "test", id = "71e1e6bf90a84b73881ba863165461a7" }]

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "test-d1"
database_id = "54b87054-2dd6-41a1-8d2f-258591ec3b18"


[vars]
API_HOST = "example.com"
API_ACCOUNT_ID = "example_user"
SERVICE_X_DATA = { URL = "service-x-api.dev.example", MY_ID = 123 }