#:schema node_modules/wrangler/config-schema.json
name = "lively-dew-2cc9"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

# Duplicate preview_id to id
kv_namespaces = [
  { binding = "test", preview_id = "0fe04d28987e40429337c02661c71fb0", id = "0fe04d28987e40429337c02661c71fb0" },
]

# Run `wrangler publish --env production` when happy
[env.production]
kv_namespaces = [{ binding = "test", id = "71e1e6bf90a84b73881ba863165461a7" }]


# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Worker, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/workers/configuration/secrets/
# [vars]
# MY_VARIABLE = "production_value"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "test-d1"
database_id = "54b87054-2dd6-41a1-8d2f-258591ec3b18"


[vars]
API_HOST = "example.com"
API_ACCOUNT_ID = "example_user"
SERVICE_X_DATA = { URL = "service-x-api.dev.example", MY_ID = 123 }